'use client';
import {useEffect,useRef,useState} from 'react';
type Paper={id:string;title:string;authors:string;year:string;journal:string;abstract:string;types:string[];url:string};
export default function LiveStudies({query,category}:{query:string;category:string}){
 const [papers,setPapers]=useState<Paper[]>([]),[total,setTotal]=useState(0),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[checked,setChecked]=useState('');const cursor=useRef<string|undefined>(undefined),controller=useRef<AbortController|null>(null),requestId=useRef(0),loading=useRef(false);
 async function load(append=false){if(append&&loading.current)return;controller.current?.abort();controller.current=new AbortController();const id=++requestId.current;loading.current=true;setBusy(true);setError('');try{const params=new URLSearchParams({q:query.trim(),category});if(append&&cursor.current)params.set('cursor',cursor.current);const r=await fetch('/api/products/research?'+params,{signal:controller.current.signal});const d=await r.json() as {papers:Paper[];total:number;cursor?:string;more:boolean;checkedAt:string;error?:string};if(!r.ok)throw Error(d.error||'Library unavailable');if(id!==requestId.current)return;setPapers(previous=>append?[...previous,...(d.papers as Paper[]).filter(p=>!previous.some(a=>a.id===p.id))]:d.papers);cursor.current=d.cursor;setMore(d.more);setTotal(d.total);setChecked(d.checkedAt)}catch(e){if(id===requestId.current&&!(e instanceof DOMException&&e.name==='AbortError'))setError(e instanceof Error?e.message:'Library unavailable')}finally{if(id===requestId.current){loading.current=false;setBusy(false)}}}
 useEffect(()=>{++requestId.current;controller.current?.abort();cursor.current=undefined;setPapers([]);setMore(false);setError('');const timer=setTimeout(()=>void load(),500);return()=>{clearTimeout(timer);controller.current?.abort();++requestId.current}},[query,category]);
 return <section className="live-product-library discovery-note" id="live-research"><p className="eyebrow">CONNECTED RESEARCH LIBRARY</p><h2>{query.trim()?`Research on “${query.trim()}”`:'Keep following the evidence.'}</h2><p>Live papers from Europe PMC’s PubMed index. Search any ingredient or treatment, then keep loading results. A paper appearing here does not mean it supports the advertised promise.</p><p className="small">{checked&&`${total.toLocaleString()} matching records · fetched ${new Date(checked).toLocaleString()}. `}The prepared assessments below do not change automatically when new papers arrive.</p><button className="quiet" disabled={busy} onClick={()=>void load()}>Refresh sources</button>{error&&<p className="error" role="alert">{error} <button className="quiet" onClick={()=>void load(papers.length>0)}>Retry</button> <a href={`https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(query.trim()||category+' wellness treatment')}`} target="_blank" rel="noopener noreferrer">Open PubMed ↗</a></p>}{busy&&<p role="status">Finding research…</p>}{!busy&&!error&&checked&&!papers.length&&<p>No papers match these terms. Try the ingredient’s name or a shorter treatment name.</p>}<div className="live-papers">{papers.map(p=><article className="live-paper" key={p.id}><p className="small">{p.journal} · {p.year} · {p.types.slice(0,3).join(' · ')}</p><h3><a href={p.url} target="_blank" rel="noopener noreferrer">{p.title} ↗</a></h3><details><summary>Read the abstract</summary><p>{p.abstract||'No abstract supplied. Open the original record to inspect the study.'}</p><p className="small">{p.authors}</p></details></article>)}</div>{more&&<button className="secondary" disabled={busy} onClick={()=>void load(true)}>Load more sources →</button>}{!more&&papers.length>0&&!busy&&<p className="small">You’ve reached the available results for this search. Try another topic to explore more.</p>}</section>;
}
