'use client';
import {useEffect,useState} from 'react';
import {researchTerms,type DigestPaper} from './evidence';
import ClaimReport from './claim-report';
import ResearchContext from './research-context';
type Result={claim:string;papers:DigestPaper[];total:number;error?:string};
export default function BatchResearch({claims}:{claims:string[]}){
 const [results,setResults]=useState<Result[]>([]),[busy,setBusy]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{const abort=new AbortController();setResults([]);setBusy(true);async function run(){for(const claim of claims){if(abort.signal.aborted)return;try{const query=researchTerms(claim);if(!query)throw Error('This statement needs a more specific research topic.');const r=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query}),signal:abort.signal});const d=await r.json() as {papers:DigestPaper[];total:number;error?:string};if(!r.ok)throw Error(d.error||'Search unavailable.');setResults(previous=>[...previous,{claim,papers:d.papers,total:d.total}]);}catch(e){if(abort.signal.aborted)return;setResults(previous=>[...previous,{claim,papers:[],total:0,error:e instanceof Error?e.message:'Search unavailable.'}]);}}setBusy(false)}run();return()=>abort.abort()},[claims,retry]);
 return <section className="results" aria-label="Selected statement reports"><p className="eyebrow">YOUR REEL, CLAIM BY CLAIM</p><h2>{claims.length} statements. Separate evidence trails.</h2><p role="status">{busy?`Searching statement ${Math.min(results.length+1,claims.length)} of ${claims.length}…`:'Searches complete. Open each statement to inspect its sources and ask Sage for its summary.'}</p>{results.map((r,i)=><details className="paper" key={r.claim} open={results.length===1}><summary><span className="source-number">{i+1}</span><h3>{r.claim}</h3></summary>{r.error?<p role="alert">{r.error}</p>:<><p>{r.total.toLocaleString()} matching records · up to 8 papers shown. Search matches alone do not establish whether this statement is true.</p>{r.papers.map((p,n)=><details className="paper" key={p.id}><summary>{n+1}. {p.title}</summary><p>{p.abstract||'No abstract supplied.'}</p><a href={p.url} target="_blank" rel="noopener noreferrer">Inspect the source ↗</a></details>)}<ResearchContext claim={r.claim} papers={r.papers}/><ClaimReport claim={r.claim} papers={r.papers}/></>}</details>)}{!busy&&results.some(r=>r.error)&&<button className="secondary" onClick={()=>setRetry(x=>x+1)}>Retry statement searches</button>}<p className="small">Assess statements one at a time to keep on-device analysis manageable. Research literacy, not medical advice.</p></section>
}
