'use client';
import {useEffect,useRef,useState} from 'react';
import {Sparkles} from 'lucide-react';
import type {DigestPaper} from './evidence';
import {validateAssessment,type Assessment} from './evidence';
export default function ClaimReport({claim,papers,onAssessment}:{claim:string;papers:DigestPaper[];onAssessment?:(report:Assessment)=>void}){
 const [report,setReport]=useState<Assessment|null>(null),[status,setStatus]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const worker=useRef<Worker|null>(null);
 useEffect(()=>{setReport(null);setStatus('');setError('');setBusy(false);worker.current?.terminate();worker.current=null;return()=>worker.current?.terminate()},[claim,papers]);
 const adhdRestlessness=/\badhd\b|attention.deficit/i.test(claim)&&/sit|still|restless|fidget|place|minute/i.test(claim);
 function analyze(){
  setBusy(true);setError('');setStatus('Preparing Sage’s claim assessment…');
  const w=new Worker('/claim-worker.js',{type:'module'});worker.current=w;
  w.onerror=()=>{setError('Sage’s model could not load on this device. Try again; the papers remain available above.');setBusy(false);w.terminate()};
  w.onmessage=e=>{if(e.data.status==='progress')setStatus(e.data.message);else if(e.data.status==='done'){const checked=validateAssessment(e.data.report,papers);if(checked){setReport(checked);onAssessment?.(checked);}else setError('Sage could not produce an assessment with verifiable source excerpts. No verdict has been assigned. Try again or inspect the papers above.');setBusy(false);setStatus('');w.terminate()}else if(e.data.status==='error'){setError(e.data.message);setBusy(false);setStatus('');w.terminate()}};
  w.postMessage({claim,papers:papers.map((p,i)=>({number:i+1,title:p.title,abstract:p.abstract.slice(0,2400),types:p.types}))});
 }
 return <section className="simple-report" aria-labelledby="digest-title"><p className="eyebrow">SAGE’S TAKE ON YOUR CLAIM</p><h3 id="digest-title">Let’s answer the actual question.</h3><p className="exact-claim">“{claim}”</p>{adhdRestlessness&&<div className="direct-assessment"><span className="verdict">Possible symptom; not enough to tell</span><p className="digest-intro">Difficulty sitting still can occur with ADHD. But being unable to sit in one place for five minutes, by itself, does not tell you whether you have ADHD.</p><p>ADHD assessment looks at a persistent pattern of symptoms, their effect on everyday life, and whether they occur across settings. Stress, sleep problems and anxiety can also produce similar difficulties. So the “might” is possible, but this is not a reliable five-minute test.</p><a href="https://www.nimh.nih.gov/health/publications/attention-deficit-hyperactivity-disorder-what-you-need-to-know" target="_blank" rel="noopener noreferrer">Source: NIMH’s ADHD diagnostic guidance</a><p className="small">This is a sourced explanation of this symptom claim, separate from the live paper assessment below. It does not diagnose you.</p></div>}
 {report?<div aria-live="polite"><span className="verdict">{report.verdict}</span><p className="digest-intro">{report.answer}</p><h4>Why Sage says that</h4>{report.findings.map((f,i)=><div className="digest-finding" key={i}><a href={papers[f.paper-1].url} target="_blank" rel="noopener noreferrer">Paper {f.paper}: {papers[f.paper-1].title}</a><p>{f.meaning}</p><details><summary>Check the supporting words</summary><blockquote>{f.quote}</blockquote></details></div>)}<h4>What these papers can’t settle</h4><p>{report.limits}</p><p className="small">Experimental AI assessment of the retrieved abstract excerpts, not full papers or a systematic review. Source excerpts are checked against the abstracts; interpretation still needs human judgment.</p></div>:papers.some(p=>p.abstract)?<><p>Sage can compare this exact claim with the retrieved abstracts and explain what supports it, what challenges it, and what remains unknown — with source links.</p><p className="small">Free on-device AI · first use downloads several hundred MB and may take a few minutes. Uses graphics acceleration when available, with a CPU-compatible model otherwise. Your claim and papers stay on this device during analysis. Model files come from Hugging Face.</p><button className="primary" disabled={busy} onClick={analyze}><Sparkles size={18}/>{busy?'Sage is weighing the evidence…':'Ask Sage about this claim'}</button>{busy&&<button className="quiet" onClick={()=>{worker.current?.terminate();setBusy(false);setStatus('Analysis cancelled.')}}>Cancel analysis</button>}</>:<p>No usable abstracts were found for this claim. There is not enough evidence here to assess it. That does not mean it is false.</p>}
 {status&&<p className="speech-status" role="status">{status}</p>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
