'use client';
import {useEffect,useRef,useState} from 'react';
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export default function InstallApp(){
 const pending=useRef<InstallEvent|null>(null),[ready,setReady]=useState(false),[installed,setInstalled]=useState(false),[open,setOpen]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const standalone=()=>setInstalled(window.matchMedia('(display-mode: standalone)').matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone));standalone();const receive=(e:Event)=>{e.preventDefault();pending.current=e as InstallEvent;setReady(true)};const done=()=>{pending.current=null;setReady(false);setInstalled(true);setOpen(false)};window.addEventListener('beforeinstallprompt',receive);window.addEventListener('appinstalled',done);if('serviceWorker'in navigator)void navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>{window.removeEventListener('beforeinstallprompt',receive);window.removeEventListener('appinstalled',done)}},[]);
 async function install(){setMessage('');const event=pending.current;if(!event){setOpen(true);return}try{await event.prompt();const choice=await event.userChoice;if(choice.outcome!=='accepted'){setOpen(true);setMessage('You can install later using your browser’s menu.')}}catch{setOpen(true);setMessage('Use the steps below to add De-Tok to your home screen.')}finally{pending.current=null;setReady(false)}}
 if(installed)return null;
 return <section className="install-strip" aria-label="Install De-Tok" id="install-detok"><div className="install-strip-heading"><div><strong>Keep Sage on your home screen.</strong><span> Open De-Tok in a tap.</span></div><button className="secondary" onClick={()=>void install()} aria-expanded={open}>Install De-Tok ↗</button><button className="quiet" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="install-steps">{open?'Hide steps':'How to install'}</button></div>{open&&<div id="install-steps" className="install-steps">{message&&<p role="status">{message}</p>}<p><strong>Android:</strong> Open this site in Chrome. Tap ⋮ → <strong>Add to Home screen</strong> or <strong>Install app</strong>, then confirm. {ready&&'You can also use the Install De-Tok button above.'}</p><p><strong>iPhone or iPad:</strong> Open this site in Safari. Tap <strong>Share</strong> → <strong>Add to Home Screen</strong> → <strong>Add</strong>. You may need to scroll down in the Share menu.</p><p><strong>Inside Instagram, WhatsApp or ChatGPT?</strong> Open the link in your phone’s browser first. Installation may be unavailable in the in-app browser.</p><p className="small">If you already installed De-Tok, look for it on your home screen. The browser controls whether a native install prompt is offered.</p><button className="quiet" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/');setMessage('Link copied. Paste it into Chrome or Safari.')}catch{setMessage('Copy the address from your browser and open it in Chrome or Safari.')}}}>Copy app link</button></div>}</section>;
}
