'use client';
import {useEffect,useRef,useState} from 'react';
type Reading={time:number|null;text:string;confidence:number};
export default function OcrInput({onUse}:{onUse:(text:string)=>void}){
 const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[text,setText]=useState(''),[readings,setReadings]=useState<Reading[]>([]),[language,setLanguage]=useState('eng');
 const worker=useRef<Worker|null>(null),generation=useRef(0);const video=useRef<HTMLVideoElement|null>(null);
 useEffect(()=>()=>{generation.current++;worker.current?.terminate();video.current?.pause()},[]);
 function cancel(){generation.current++;worker.current?.terminate();worker.current=null;setBusy(false);setStatus('Stopped. You can try a clearer screenshot.');}
 function recognize(image:string,id:number){return new Promise<Reading>((resolve,reject)=>{const w=new Worker('/ocr-worker.js');worker.current=w;const timeout=setTimeout(()=>{w.terminate();reject(new Error('Text recognition timed out. Try a smaller screenshot.'))},120000);w.onmessage=e=>{if(generation.current!==id){clearTimeout(timeout);w.terminate();reject(new Error('Cancelled'));return}if(e.data.status==='progress')setStatus(e.data.message);else if(e.data.status==='done'){clearTimeout(timeout);w.terminate();worker.current=null;resolve({time:null,text:String(e.data.text||'').trim(),confidence:Number(e.data.confidence)||0})}else if(e.data.status==='error'){clearTimeout(timeout);w.terminate();reject(new Error(e.data.message))}};w.onerror=()=>{clearTimeout(timeout);w.terminate();reject(new Error('The text model could not load. Check your connection.'))};w.postMessage({image,language})})}
 async function scan(file:File){const id=++generation.current;setBusy(true);setError('');setReadings([]);setText('');let url='';try{
  if(file.size>30*1024*1024)throw new Error('Choose a screenshot or video under 30 MB.');url=URL.createObjectURL(file);const found:Reading[]=[];
  if(file.type.startsWith('image/')){const r=await recognize(url,id);found.push(r)}else if(file.type.startsWith('video/')){
   const v=document.createElement('video');video.current=v;v.muted=true;v.preload='auto';v.playsInline=true;
   await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Video could not load. Try screenshots instead.')),20000);v.onloadedmetadata=()=>{clearTimeout(timer);resolve()};v.onerror=()=>{clearTimeout(timer);reject(new Error('This browser cannot read this video. Upload screenshots instead.'))};v.src=url});
   if(!Number.isFinite(v.duration)||v.duration>180)throw new Error('Use a video of 3 minutes or less.');
   const canvas=document.createElement('canvas');const scale=Math.min(1,1280/v.videoWidth);canvas.width=Math.round(v.videoWidth*scale);canvas.height=Math.round(v.videoHeight*scale);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Screenshot capture is unavailable.');
   const times=Array.from({length:6},(_,i)=>Math.max(.01,Math.min(v.duration-.05,v.duration*(i+.5)/6)));
   for(const time of times){if(generation.current!==id)throw new Error('Cancelled');await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Frame capture timed out.')),12000);v.onseeked=()=>{clearTimeout(timer);resolve()};v.currentTime=time});ctx.drawImage(v,0,0,canvas.width,canvas.height);setStatus(`Reading frame ${found.length+1} of 6…`);const r=await recognize(canvas.toDataURL('image/png'),id);found.push({...r,time})}
  }else throw new Error('Choose an image or a video.');
  if(generation.current!==id)return;const unique=[...new Set(found.map(r=>r.text).filter(Boolean))];setReadings(found);setText(unique.join('\n\n'));setStatus(unique.length?'Text found. Review it before using it.':'No readable text found. Try a clearer screenshot.');
 }catch(e){if(generation.current===id)setError(e instanceof Error?e.message:'Text recognition failed.')}finally{if(url)URL.revokeObjectURL(url);video.current=null;if(generation.current===id)setBusy(false)}}
 return <details className="ocr-panel"><summary>Read the reel’s on-screen text</summary><p>Upload a screenshot or video. Six sampled video frames are read on your device; brief captions between frames may be missed. Reel links currently supply audio only. Screenshots work best.</p><label>Text language <select value={language} disabled={busy} onChange={e=>setLanguage(e.target.value)}><option value="eng">English</option><option value="hin">Hindi + English</option></select></label><label className="upload">Choose screenshot or video<input type="file" accept="image/*,video/*" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void scan(f);e.target.value=''}}/></label><p className="small">First use downloads Tesseract text models. Files stay on this device.</p>{busy&&<button className="quiet" onClick={cancel}>Cancel</button>}{status&&<p role="status">{status}</p>}{error&&<p className="error" role="alert">{error}</p>}{readings.length>0&&<><label>Review and correct the extracted text<textarea value={text} onChange={e=>setText(e.target.value)}/></label><details><summary>Inspect sampled readings</summary>{readings.map((r,i)=><div className="frame-reading" key={i}><strong>{r.time===null?'Screenshot':`${r.time.toFixed(1)} seconds`} · OCR confidence {Math.round(r.confidence)}%</strong><p>{r.text||'No text found'}</p></div>)}<p className="small">OCR confidence is a recognition estimate, not a guarantee that the words are correct.</p></details><button className="primary" disabled={!text.trim()||busy} onClick={()=>onUse(text)}>Use this on-screen text</button></>}</details>;
}
