'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,Upload,Mic} from 'lucide-react';
type Props={value:string;onTranscript:(text:string)=>void};
export default function ReelInput({value,onTranscript}:Props){
 const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[transcript,setTranscript]=useState(''),[caption,setCaption]=useState('');const [language,setLanguage]=useState('english'),[quality,setQuality]=useState('accurate');const savedAudio=useRef<ArrayBuffer|null>(null);const worker=useRef<Worker|null>(null);const runId=useRef(0);
 useEffect(()=>()=>{runId.current++;worker.current?.terminate()},[]);
 function cancel(){runId.current++;worker.current?.terminate();worker.current=null;setBusy(false);setStatus('Cancelled. You can try again.');}
 async function transcribe(buffer:ArrayBuffer,id:number){
  savedAudio.current=buffer.slice(0);setStatus('Extracting and decoding the audio…');
  const context=new AudioContext();let decoded:AudioBuffer;
  try{decoded=await context.decodeAudioData(buffer)}catch{throw new Error('This browser cannot decode this file’s audio. Try an MP4, M4A, MP3, or WAV file, or use another browser.')}finally{await context.close()}
  if(decoded.duration>180)throw new Error('Use a clip of 3 minutes or less for on-device transcription.');
  if(id!==runId.current)return;
  const offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*16000),16000);const source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();const mono=await offline.startRendering();const audio=mono.getChannelData(0);let peak=0;for(const n of audio)peak=Math.max(peak,Math.abs(n));if(peak<.0001)throw new Error('No audible sound was detected. Paste the on-screen claim instead.');
  if(id!==runId.current)return;
  await new Promise<void>((resolve,reject)=>{const w=new Worker('/transcribe-worker.js',{type:'module'});worker.current=w;const timeout=setTimeout(()=>{w.terminate();reject(new Error('Transcription timed out. Try a shorter clip or a faster device.'))},900000);w.onmessage=e=>{if(id!==runId.current){clearTimeout(timeout);w.terminate();resolve();return}if(e.data.status==='progress')setStatus(e.data.message);if(e.data.status==='done'){clearTimeout(timeout);w.terminate();worker.current=null;const text=String(e.data.text||'').trim();if(!text)reject(new Error('No speech was recognized. Please check the clip.'));else{setTranscript(text);setStatus('Transcript ready. Review it before checking the claim.');resolve()}}if(e.data.status==='error'){clearTimeout(timeout);w.terminate();worker.current=null;reject(new Error(e.data.message))}};w.onerror=()=>{clearTimeout(timeout);w.terminate();worker.current=null;reject(new Error('The speech model could not load. Check your connection; this feature needs model downloads from Hugging Face and jsDelivr.'))};w.postMessage({audio,language,quality},[audio.buffer]);});
 }
 async function fromLink(){const match=value.match(/https?:\/\/[^\s]+/);if(!match){setError('Paste a public Instagram reel link in the box above.');return}const id=++runId.current;setBusy(true);setError('');setTranscript('');setCaption('');savedAudio.current=null;setStatus('Retrieving the reel’s media…');try{const r=await fetch('/api/reel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:match[0]})});const data=await r.json() as {url?:string;audioBase64?:string;caption?:string;error?:string};if(!r.ok||(!data.url&&!data.audioBase64))throw new Error(data.error||'Media not available.');if(id!==runId.current)return;setCaption(data.caption||'');if(data.audioBase64){const binary=atob(data.audioBase64);const audio=Uint8Array.from(binary,c=>c.charCodeAt(0));await transcribe(audio.buffer,id);return}setStatus('Fetching the audio track…');const media=await fetch('/api/media?src='+encodeURIComponent(data.url!));if(!media.ok)throw new Error(await media.text());const bytes=await media.arrayBuffer();if(bytes.byteLength>30*1024*1024)throw new Error('This clip exceeds the 30 MB limit.');await transcribe(bytes,id)}catch(e){if(id===runId.current)setError(e instanceof Error?e.message:'Could not transcribe the reel.')}finally{if(id===runId.current)setBusy(false)}}
 async function fromFile(file:File){const id=++runId.current;setBusy(true);setError('');setTranscript('');setCaption('');savedAudio.current=null;try{if(file.size>30*1024*1024)throw new Error('Choose a file under 30 MB.');await transcribe(await file.arrayBuffer(),id)}catch(e){if(id===runId.current)setError(e instanceof Error?e.message:'Could not transcribe the file.')}finally{if(id===runId.current)setBusy(false)}}
 async function retry(){if(!savedAudio.current)return;const id=++runId.current;setBusy(true);setError('');try{await transcribe(savedAudio.current.slice(0),id)}catch(e){if(id===runId.current)setError(e instanceof Error?e.message:'Transcription failed.')}finally{if(id===runId.current)setBusy(false)}}
 return <div className="reel-tools"><div className="speech-options"><label>Spoken language<select value={language} disabled={busy} onChange={e=>setLanguage(e.target.value)}><option value="english">English</option><option value="hindi">Hindi / Hinglish</option><option value="auto">Detect another language</option></select></label><label>Transcription<select value={quality} disabled={busy} onChange={e=>setQuality(e.target.value)}><option value="accurate">Better accuracy</option><option value="fast">Faster, smaller download</option></select></label></div><div className="reel-actions"><button className="secondary" onClick={fromLink} disabled={busy}><Mic size={17}/> Extract & transcribe reel</button><label className={busy?'upload disabled':'upload'}><Upload size={17}/> Upload video or audio<input type="file" accept="video/*,audio/*" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void fromFile(f);e.target.value=''}}/></label></div><p className="small">Public Instagram links · clips up to 3 minutes / 30 MB. Speech processing runs on your device; the first use downloads a model. Better accuracy needs a larger download and can take several minutes.</p>{busy&&<button className="quiet" onClick={cancel}>Cancel processing</button>}{status&&<p role="status" className="speech-status"><Download size={16}/>{status}</p>}{error&&<p className="error" role="alert">{error}</p>}{transcript&&<div className="transcript-review"><label htmlFor="speech">Review and correct the transcript</label><textarea id="speech" value={transcript} onChange={e=>setTranscript(e.target.value)}/><p className="small">Speech recognition can miss words, numbers, negations, and non-English speech. On-screen text is not extracted.</p><button className="secondary" disabled={busy} onClick={retry}>Transcribe again with these settings</button><button className="primary" disabled={busy} onClick={()=>onTranscript(transcript)}>Use this transcript</button></div>}{caption&&<details><summary>Reel caption</summary><p>{caption}</p><button className="secondary" onClick={()=>onTranscript(caption)}>Use caption instead</button></details>}</div>
}
