'use client';
import {useEffect,useState} from 'react';
import type {DigestPaper} from './evidence';
export type Receipt={claim:string;verdict:string;answer:string;limits:string;papers:DigestPaper[];kind:string};
type Saved=Receipt&{id:string;date:string};
const key='detok-reports-v1';
function lines(text:string,width:number,ctx:CanvasRenderingContext2D){const result:string[]=[];let line='';for(const word of text.split(/\s+/)){const next=line?line+' '+word:word;if(ctx.measureText(next).width>width&&line){result.push(line);line=word}else line=next}if(line)result.push(line);return result;}
export async function makeEvidenceCard(r:Receipt){
 await document.fonts.ready;const c=document.createElement('canvas');c.width=1080;c.height=1500;const context=c.getContext('2d');if(!context)throw new Error('Image export is unavailable on this device.');const ctx:CanvasRenderingContext2D=context;
 ctx.fillStyle='#f5f0ff';ctx.fillRect(0,0,1080,1500);ctx.fillStyle='#513976';ctx.font='58px "EB Garamond", Georgia, serif';ctx.fillText('de-tok ✳',70,95);ctx.font='26px "EB Garamond", Georgia, serif';ctx.fillText('EVIDENCE RECEIPT · '+new Date().toLocaleDateString(),70,144);
 let y=220;function section(label:string,text:string,max:number,font=34){ctx.fillStyle='#7153a6';ctx.font='25px "EB Garamond", Georgia, serif';ctx.fillText(label,70,y);y+=43;ctx.fillStyle='#30253d';ctx.font=`${font}px "EB Garamond", Georgia, serif`;const ls=lines(text,940,ctx);for(const line of ls.slice(0,max)){ctx.fillText(line,70,y);y+=font+10}if(ls.length>max){ctx.fillText('…',70,y);y+=font+10}y+=26;}
 section('THE CLAIM',r.claim,4,40);section(r.verdict.toUpperCase(),r.answer,7);section('WHAT REMAINS UNCERTAIN',r.limits,4,29);
 ctx.fillStyle='#513976';ctx.font='24px "EB Garamond", Georgia, serif';ctx.fillText(`${r.kind} · ${r.papers.length} linked sources`,70,1330);ctx.fillText('Research literacy, not medical advice. Read the sources.',70,1370);ctx.fillText(location.origin.replace('https://',''),70,1410);
 return await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Could not create image.')),'image/png'));
}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
export default function ReportShelf({current}:{current:Receipt|null}){
 const [saved,setSaved]=useState<Saved[]>([]),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(raw))setSaved(raw.filter(r=>r&&typeof r.id==='string'&&typeof r.claim==='string'&&typeof r.answer==='string'&&Array.isArray(r.papers)).slice(0,30))}catch{setMessage('Saved reports could not be read on this device.')}},[]);
 function persist(next:Saved[]){try{localStorage.setItem(key,JSON.stringify(next));setSaved(next);return true}catch{setMessage('This browser could not save the report. Export it as a file instead.');return false}}
 function save(){if(!current)return;const item={...current,id:crypto.randomUUID(),date:new Date().toISOString(),papers:current.papers.map(p=>({...p,abstract:p.abstract.slice(0,1800)}))};if(persist([item,...saved].slice(0,30)))setMessage('Saved on this device. Your latest 30 reports are kept.');}
 async function card(){if(!current)return;setBusy(true);try{const blob=await makeEvidenceCard(current);download(blob,'de-tok-evidence-card.png');setMessage('Evidence card downloaded. Export the source receipt too to include clickable links.')}catch(e){setMessage(e instanceof Error?e.message:'Card export failed.')}finally{setBusy(false)}}
 async function share(){if(!current)return;const text=`${current.claim}\n${current.verdict}\n${current.answer}\nUncertainty: ${current.limits}\n${current.kind}\nSources:\n${current.papers.map(p=>p.title+'\n'+p.url).join('\n')}\nResearch literacy, not medical advice.`;setBusy(true);try{const file=new File([await makeEvidenceCard(current)],'de-tok-evidence-card.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})&&navigator.share)await navigator.share({files:[file],title:'De-Tok evidence receipt',text});else if(navigator.share)await navigator.share({title:'De-Tok evidence receipt',text});else{download(file,file.name);download(new Blob([text],{type:'text/plain'}),'de-tok-sources.txt');setMessage('Card and source links downloaded.')}}catch(e){setMessage(e instanceof DOMException&&e.name==='AbortError'?'Sharing cancelled.':'Sharing is unavailable. Use Download card or Export receipt.')}finally{setBusy(false)}}
 const compared=selected.map(id=>saved.find(r=>r.id===id)).filter((r):r is Saved=>Boolean(r));
 return <section className="report-shelf"><p className="eyebrow">KEEP THE CURIOSITY</p><h2>Your evidence shelf</h2><p>Saved only in this browser, on this device. Clearing browser data removes them. Exports include the claim, assessment and source links.</p>{current&&<div className="receipt-actions"><button className="secondary" onClick={save}>Save this report</button><button className="secondary" disabled={busy} onClick={card}>Download evidence card</button><button className="secondary" disabled={busy} onClick={share}>Share card + sources</button><button className="quiet" onClick={()=>download(new Blob([JSON.stringify({...current,date:new Date().toISOString()},null,2)],{type:'application/json'}),'de-tok-receipt.json')}>Export receipt</button></div>}{message&&<p role="status">{message}</p>}{saved.length===0?<p className="small">Your saved reports will appear here. Search for a claim or explore a sourced brief to begin.</p>:<><p className="small">Select two reports to compare their answers, limitations and source overlap. This does not produce a new verdict.</p>{saved.map(r=><article className="saved-report" key={r.id}><label><input type="checkbox" checked={selected.includes(r.id)} disabled={selected.length>=2&&!selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id))}/> Compare</label><h3>{r.claim}</h3><p className="small">{new Date(r.date).toLocaleDateString()} · {r.verdict} · {r.kind}</p><details><summary>Read saved report</summary><p>{r.answer}</p><p>{r.limits}</p>{r.papers.map(p=><p key={p.id}><a href={p.url} target="_blank" rel="noopener noreferrer">{p.title}</a></p>)}</details><button className="quiet" onClick={()=>{if(confirm('Delete this saved report from this device?')){persist(saved.filter(x=>x.id!==r.id));setSelected(selected.filter(id=>id!==r.id))}}}>Delete</button></article>)}</>}{compared.length===2&&<div className="comparison"><h3>Two reports, side by side</h3><div className="comparison-scroll"><table><thead><tr><th>Look at</th>{compared.map(r=><th key={r.id}>{r.claim}</th>)}</tr></thead><tbody>{[['Conclusion','verdict'],['Explanation','answer'],['Uncertainty','limits'],['Report type','kind']].map(([label,field])=><tr key={field}><th>{label}</th>{compared.map(r=><td key={r.id}>{r[field as 'answer']}</td>)}</tr>)}<tr><th>Sources</th>{compared.map(r=><td key={r.id}>{r.papers.map(p=><p key={p.id}><a href={p.url} target="_blank" rel="noopener noreferrer">{p.title}</a></p>)}</td>)}</tr></tbody></table></div><p>Shared source records: {compared[0].papers.filter(p=>compared[1].papers.some(q=>q.url===p.url)).length}. Different conclusions can reflect different populations, questions, evidence or assessment errors. Inspect the sources before resolving a disagreement.</p></div>}</section>;
}
