import type {DigestPaper} from './evidence';
export function studyContext(p:DigestPaper,claim:string){
 const labels=p.types.join(' ');const text=p.title+' '+p.abstract;
 const design=/meta.analysis|systematic review/i.test(labels)?'Evidence synthesis':/randomized controlled trial/i.test(labels)?'Randomized trial':/clinical trial/i.test(labels)?'Clinical trial':/observational|cohort|case.control|cross.sectional/i.test(labels+' '+text)?'Observational study':/review/i.test(labels)?'Review':'Design not established';
 const explanation=design==='Evidence synthesis'?'Combines studies. Its usefulness depends on their quality, relevance, and how the review was conducted.':design==='Randomized trial'?'Random allocation can help test an intervention’s effect. Bias, precision, and relevance still matter.':design==='Observational study'?'Can identify associations. Confounding and reverse causation can limit causal conclusions.':design==='Review'?'Discusses existing research; this label alone does not establish a systematic search.':'Inspect the methods before drawing conclusions about cause and effect.';
 const sample=p.abstract.match(/\b(?:n\s*=\s*[\d,]+|[\d,]+\s+(?:participants|patients|adults|subjects|children|women|men|mice|rats))\b/i)?.[0]||'Not identified in abstract';
 const words=[...new Set(claim.toLowerCase().match(/[a-z]{4,}/g)||[])].filter(w=>!['that','this','have','with','should','everyone','claim','might','about','people','would','could','there','their'].includes(w));
 const matches=words.filter(w=>text.toLowerCase().includes(w));
 return {design,explanation,sample,matches};
}
export default function ResearchContext({papers,claim}:{papers:DigestPaper[];claim:string}){
 return <section className="research-context"><p className="eyebrow">HOW MUCH CAN THESE PAPERS TELL US?</p><h3>Study clues, with the uncertainty intact.</h3><p>Study design is one clue, not a quality score. Risk of bias, inconsistent findings, relevance and precision require a fuller assessment. <a href="https://training.cochrane.org/handbook/current/chapter-14" target="_blank" rel="noopener noreferrer">How evidence certainty is assessed</a></p>{papers.map((p,i)=>{const c=studyContext(p,claim);return <details key={p.id}><summary>Paper {i+1} · {c.design}</summary><p>{c.explanation}</p><dl><dt>Publication labels from PubMed</dt><dd>{p.types.join(', ')||'None supplied'}</dd><dt>Sample wording found in abstract</dt><dd>{c.sample}</dd><dt>Words shared with your claim</dt><dd>{c.matches.join(', ')||'No direct keyword overlap'}</dd></dl><p className="small">Keyword overlap does not establish relevance. Sample wording can refer to one group or another study; check the methods. Study quality has not been graded.</p><a href={p.url} target="_blank" rel="noopener noreferrer">Inspect original paper</a></details>})}</section>;
}
