'use client';
import {useEffect,useState} from 'react';
import {Mail,RefreshCw,Check} from 'lucide-react';
type Message={id:string;message:string;category:string;createdAt:number;read:number};
export default function Inbox(){
 const [messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('All'),[more,setMore]=useState(false),[saving,setSaving]=useState('');
 async function load(append=false){setBusy(true);setError('');try{const cursor=append&&messages.length?`?before=${messages.at(-1)!.createdAt}`:'';const r=await fetch('/api/feedback/inbox'+cursor,{cache:'no-store'});const d=await r.json() as {messages?:Message[];error?:string};if(!r.ok||!d.messages)throw new Error(d.error);setMessages(old=>append?[...old,...d.messages!]:d.messages!);setMore(d.messages.length===50)}catch(e){setError(e instanceof Error?e.message:'Could not load feedback.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function mark(m:Message){setSaving(m.id);setError('');try{const r=await fetch('/api/feedback/inbox',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:m.id,read:!m.read})});if(!r.ok)throw new Error('Could not update this message. Try again.');setMessages(old=>old.map(p=>p.id===m.id?{...p,read:p.read?0:1}:p))}catch(e){setError(e instanceof Error?e.message:'Could not update feedback.')}finally{setSaving('')}}
 const visible=messages.filter(m=>filter==='All'||filter==='Unread'?!m.read||filter==='All':m.category===filter);
 return <><div className="inbox-controls"><div className="inbox-filters" aria-label="Filter feedback">{['All','Unread','Experience','Idea','Bug'].map(f=><button className={filter===f?'active':''} aria-pressed={filter===f} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><button className="quiet" disabled={busy} onClick={()=>load()}><RefreshCw size={17}/>Refresh</button></div><p className="small">{messages.filter(m=>!m.read).length} unread in {messages.length} loaded messages</p>{error&&<p className="error" role="alert">{error}</p>}{busy&&!messages.length?<p role="status">Opening your inbox…</p>:!visible.length?<div className="inbox-empty"><Mail size={32}/><h2>{messages.length?'No messages in this view.':'Your inbox is ready.'}</h2><p>{messages.length?'Choose another filter to see more feedback.':'When someone sends feedback through the welcome box, it will appear here.'}</p></div>:<div className="inbox-messages">{visible.map(m=><article key={m.id} className={`inbox-message ${m.read?'':'unread'}`}><div className="message-meta"><span className="verdict">{m.category}</span><span className="small">{new Date(m.createdAt).toLocaleString()}</span>{!m.read&&<span className="unread-label">Unread</span>}</div><p className="feedback-content">{m.message}</p><button className="secondary" disabled={saving===m.id} onClick={()=>mark(m)}><Check size={15}/>{m.read?'Mark unread':'Mark read'}</button></article>)}</div>}{more&&<button className="secondary" disabled={busy} onClick={()=>load(true)}>{busy?'Loading…':'Load older feedback'}</button>}</>;
}
